- name: Enable CSM in settings
  run: |
    sed -i 's/enable_client_modding.*false/enable_client_modding", "true"/' src/defaultsettings.cpp || true
    echo "enable_client_modding = true" >> minetest.conf.example
