name: Build Luanti Android (with CSM)

on:
  workflow_dispatch:   # Permite ejecutar manualmente
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk unzip git

      - name: Enable CSM in settings
        run: |
          sed -i 's/enable_client_modding.*false/enable_client_modding", "true"/' src/defaultsettings.cpp || true
          echo "enable_client_modding = true" >> minetest.conf.example

      - name: Build APK (armeabi-v7a - 32bit)
        run: |
          cd build/android
          ./gradlew assembleDebug -PABI_FILTERS=armeabi-v7a
          cd ../..
          mkdir -p artifacts
          cp build/android/app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk artifacts/minetest-android-32bit.apk || true

      - name: Build APK (arm64-v8a - 64bit)
        run: |
          cd build/android
          ./gradlew assembleDebug -PABI_FILTERS=arm64-v8a
          cd ../..
          mkdir -p artifacts
          cp build/android/app/build/outputs/apk/debug/app-arm64-v8a-debug.apk artifacts/minetest-android-64bit.apk || true

      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: luanti-apks
          path: artifacts/*.apk
